name: challenge

on: push

jobs:
    first:
         name: copy file
         runs-on: ubuntu-latest
         steps:
         - name: checkout
           uses: actions/checkout@v2
         - name: make dir
           run: mkdir -p .challenge/workflows
         - name: copy to file
           run: cp  .actions/workflows .challenge/workflows

    second:
          name: test
          runs-on: windows-latest
          steps:
            run: echo "iF first and second fine will do third"

    third:
         name: print the date
         runs-on: macos-latest
         steps:
           run: date '+%A %W %Y %X'

    fourth:
          name: dependencies
          needs: [first, second]
          runs-on: ubuntu-latest
          steps:
            run: echo "everything is fine"